#! /bin/bash

# Script to run Oerlemans-spm model
echo ''
echo '## Running oerlemans-spm ##'

# Paths
parfile=${1}
outname=${2}
env_name='oerlemans_env'
conda_path='/home/sergio/'  # change if needed

echo '* Parameter file --> '${parfile}''
echo '* Output directory name --> '${outname}''

# Create directories if needed
locdir=$(pwd)
locouttemp=${locdir}/temp/${outname}/

if [ -d ${locouttemp} ]; then
echo '* '${outname}' already created'
else
mkdir ${locouttemp}
echo '* '${outname}' created'
fi


# Copy oerlemans_main.py and parameters
cp ${locdir}/libs/oerlemans_main.py ${locouttemp}
cp ${locdir}/libs/plot_results.py ${locouttemp}
cp -r ${locdir}/libs/ ${locouttemp}
cp ${locdir}/par/${parfile} ${locouttemp}/params.py

# Execute oerlemans_main.py
cd ${locouttemp}
echo ''
echo '** Starting simulation **'
chmod +x oerlemans_main.py
chmod +x plot_results.py

source ${conda_path}/anaconda3/etc/profile.d/conda.sh

conda activate ${env_name}
python3 oerlemans_main.py

echo '** Plotting results ... '
python3 plot_results.py
conda deactivate

# Move to output and clean
rm __pycache__/*
rmdir __pycache__
rm libs/__pycache__/*
rmdir libs/__pycache__

rm libs/*
rmdir libs/

rm oerlemans_main.py
rm plot_results.py
cd ..
cp -r ${outname} ../output/

rm ${outname}/*
rmdir ${outname}

echo '** Simulation finished **'
echo ''



